###
GET http://localhost:8080/notes

###
POST http://localhost:8080/notes
Content-Type: application/json

{
  "title": "Note 1",
  "body": "body",
  "folderID": 0
}

###
DELETE http://localhost:8080/notes/1

###
PUT http://localhost:8080/notes/2
Content-Type: application/json

{
  "title": "new note",
  "body": "new body",
  "folderID": 1
}

###
GET http://localhost:8080/folders

###
POST http://localhost:8080/folders
Content-Type: application/json

{
  "name": "Folder 1"
}

###
DELETE http://localhost:8080/folders/1

###
PUT http://localhost:8080/folders/2
Content-Type: application/json

{
  "name": "new folder name"
}

###
GET http://localhost:8080/reminders

###
POST http://localhost:8080/reminders
Content-Type: application/json

{
  "body": "Reminder 1",
  "noteID": 1
}
